#!/bin/bash
# deploy_now.sh - 一键部署指南

echo "🚀 HopeHub 立即部署"
echo "=================="
echo ""
echo "步骤1: 在Render页面填写"
echo "------------------------"
echo "Build Command:"
echo "  pip install -r requirements.txt"
echo ""
echo "Start Command:"
echo "  cd production && python stripe_server.py"
echo ""
echo "步骤2: 点击 Create Web Service"
echo ""
echo "步骤3: 部署后添加环境变量"
echo "------------------------"
echo "STRIPE_SECRET_KEY=sk_test_51PytZfCdh5c7XDJbzyKGKaM1gQ4ZmHv7fl0KbUd3htuQtc2xhjuAYmyntiFnfbrOvxUstg4QieVEBvVjFlb9lHhp0071q2E9Sm"
echo ""
echo "STRIPE_PUBLISHABLE_KEY=pk_test_51PytZfCdh5c7XDJbxFrbSaZX55doWLbrZ77iutZTR8vlrQcogvQJSFNWkH4fJbqDzZo551D2ZSsw6dqFvQt9btrc00C0B2mrqr"
echo ""
echo "步骤4: 创建前端静态网站"
echo "------------------------"
echo "Name: hopehub-frontend"
echo "Publish directory: ./website"
echo ""
echo "🎯 10分钟后访问: https://hopehub.x1000.ai"
